WebApplication2/WebApplication2/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class IletisimController : Controller
    {
        // GET: Iletisim
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/KategorilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class KategorilerController : Controller
    {
        // GET: Kategoriler
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/YayincilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class YayincilarController : Controller
    {
        // GET: Yayincilar
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ana Sayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <div class="container">
                    <div class="col-md-4">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Katagoriler", "Index", "Kategoriler")</li>
                            <li>@Html.ActionLink("Yazarlar", "Index", "Yazarlar")</li>
                            <li>@Html.ActionLink("Yayıncılar", "Index", "Yayincilar")</li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <div class="row" style="padding-top:13px;">
                            <div class="col-md-2 col-xs-2"></div>
                            <div class="col-md-6 col-xs-6">
                                @Html.TextBox("Arama", null, "arama")
                            </div>
                            <div class="col-md-2 col-xs-2">                               
                                    <input type="button" value="Ara" />                            
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Kayıt Ol", "", "Home")</li>
                            <li>@Html.ActionLink("Üye Girişi", "", "Home")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
        @RenderBody()
        <hr />
    <div class="container body-content">
        <footer class="panel-footer">
            <div class="container">
                <div class="col-md-1"></div>
                <div class="col-md-5">
                    <center> <div>Sosyal Medya Hesapları</div></center> 
                    <div class="row">
                            <div class="col-md-3">
                                <img style="height:50px;width:50px;" src="https://lh3.googleusercontent.com/ZZPdzvlpK9r_Df9C3M7j1rNRi7hhHRvPhlklJ3lfi5jk86Jd1s0Y5wcQ1QgbVaAP5Q=w300" alt="..." class="img-rounded">
                            </div>
                            <div class="col-md-3">
                                <img  style="height:50px;width:50px;" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRpJWx3KvFy4tAWm1qZ30hKyybk_Pev5iqv6i3Tz2TF2EQBUJOnSg" alt="..." class="img-rounded">
                            </div>
                            <div class="col-md-3">
                                <img style="height:50px;width:50px;" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR9Jnu7lyMYamsofS6hl75UQQ-6-Nibg1LiBymHpkO3zUgfRZ-EjQ" alt="..." class="img-rounded">
                            </div>
                            <div class="col-md-3">
                                <img style="height:50px;width:50px;" src="https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSBv9-c53WPt9c98tdDvWqi83zY2ljB9JU7MAhAJWxHAVsNZGZP" alt="..." class="img-rounded">
                            </div>                     
                    </div>
                </div>
                <div class="col-md-4">
                    <div> Müşteri Hizmetleri</div>

                    <div><a>@Html.ActionLink("Hakkımızda","", "Home")</a></div>
                    <div>  <a>@Html.ActionLink("Iletişim", "Index", "Iletisim")</a></div>
                </div>
                <div class="col-md-1">
                    <select id="dropdowntipo">
                        <option value="Türkçe">TR</option>
                        <option value="Ingilizce">ENG</option>
                    </select>
                </div>
            </div>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>