WebApplication2/WebApplication2/Controllers/KitapBilgiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class KitapBilgiController : Controller
    {
        // GET: KitapBilgi
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/KitapListeleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class KitapListeleController : Controller
    {
        // GET: KitapListele
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/KitapListele/Index.cshtml
@{
    ViewBag.Title = "Kitap Listele";
}

<div class="container">
    <div class="col-md-2"></div>
    <center><h2>Kitaplar</h2></center>
    <div class="panel panel-default">

        <div class="row container panel-body">
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>   
            <div class="col-md-3" style="height:275px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div style="height:80%; width:100%;"><img src="http://placehold.it/80x70" class="img-rounded" style="width:100%;height:100%;"> </div>
                    </div>

                    <div class="panel-footer"> <center> @Html.ActionLink("Kitap", "Index", "KitapBilgi")</center></div>
                </div>
            </div>         
        </div>
    </div>

    <div class="col-md-2"></div>
</div>