WebApplication2/WebApplication2/Controllers/YazarBilgiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class YazarBilgiController : Controller
    {
        // GET: YazarBilgi
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/YazarlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class YazarlarController : Controller
    {
        // GET: Yazarlar
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/Yazarlar/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default container" style="margin-top:50px;">
    <div class="panel-body">
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("Yazar", "Index", "YazarBilgi")</div></center>
    </div>
</div>