WebApplication2/WebApplication2/Controllers/YayincilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class YayincilarController : Controller
    {
        // GET: Yayincilar
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Controllers/YazarlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class YazarlarController : Controller
    {
        // GET: Yazarlar
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/Yayincilar/Index.cshtml
@{
    ViewBag.Title = "Yayin Evleri";
}

<div class="panel panel-default container" style="margin-top:100px;">
    <div class="panel-body">

        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>
        <center><div class="col-md-4" style="margin-top:20px;">@Html.ActionLink("YayınEvi", "", "Yazarlar")</div></center>

    </div>
</div>